[build]
  base = "webapp/"
  command = "npm run publish"
  publish = "dist/d2g-webapp/browser"

[[redirects]]
  from = "/fr/*"
  to = "/fr/index.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

# [[redirects]]
#   from = "/de/*"
#   to = "/de/index.html"
#   status = 200

# [[redirects]]
#   from = "/es/*"
#   to = "/es/index.html"
#   status = 200

[[redirects]]
  from = "/*"
  to = "/fr/index.html"
  status = 200