[build]
  base = "webapp/"
  command = "ng build --configuration=fr"
  publish = "dist/d2g-webapp/browser"

[[redirects]]
  from = "/fr/*"
  to = "/fr/index.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200