[tool.ruff]
line-length = 120
exclude = ["*/migrations/*"]
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "PL"
]
ignore = [
    "PLR2004",
    "PLR0912",
    "PLR0913",
    "PLR0915",
]

[tool.ruff.lint.per-file-ignores]
"manage.py" = ["PLC0415"]