# Generated by Django 5.0.3 on 2024-05-06 10:32

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

CORRECTION_TABLE = {
    "TypeDefinition": {
        "type_en": {"Trace Rifles":  "Trace Rifle",
                    "Grenade Launchers":  "Grenade Launcher",
                    "Submachine Guns": "Submachine Gun",
                    "Linear Fusion Rifles":  "Linear Fusion Rifle",
                    "Glaives":  "Glaive",
                    "Bows":  "Bow"},
        "type_fr": {"Fusils automatiques" : "Fusil automatique",
                    "Revolvers" : "Revolver",
                    "Fusils à impulsion" : "Fusil à impulsion",
                    "Fusils d'éclaireur" : "Fusil d'éclaireur",
                    "Fusils à pompe" : "Fusil à pompe",
                    "Fusils de précision" : "Fusil de précision",
                    "Fusils à fusion" : "Fusil à fusion",
                    "Mitrailleuses" : "Mitrailleuse",
                    "Pistolets" : "Pistolet",
                    "Épées" : "Épée",
                    "Fusils à rayon" : "Fusil à rayon",
                    "Pistolets-mitrailleurs" : "Pistolet-mitrailleur",
                    "Fusils à fusion linéaire" : "Fusil à fusion linéaire",
                    "Glaives" : "Glaive",
                    "Arcs" : "Arc"}
    },
    "DamageTypeDefinition": {
        "damageType_fr": {"Cinétiques": "Cinétique",
                          "Cryo-électriques": "Cryo-électrique",
                          "Solaires": "Solaire",
                          "Abyssaux": "Abyssal"}
    }
}



def correct_tables(apps, schema_editor):
    for modelName in ["TypeDefinition", "DamageTypeDefinition"]:
        model = apps.get_model("d2guessrlib", modelName)
        for fieldName in CORRECTION_TABLE[modelName].keys():
            for oldValue, newValue in CORRECTION_TABLE[modelName][fieldName].items():
                filter_dict = {fieldName: oldValue}
                update_dict = {fieldName: newValue}
                model.objects.filter(**filter_dict).update(**update_dict)

def shorten_links(apps, schema_editor):
    Weapon = apps.get_model("d2guessrlib", "Weapon")
    DamageTypeDefinition = apps.get_model("d2guessrlib", "DamageTypeDefinition")
    weapon_objects = Weapon.objects.all()
    for weapon in weapon_objects:
        weapon.iconLink = weapon.iconLink.replace('/common/destiny2_content/icons/', '')
        weapon.screenshotLink = weapon.screenshotLink.replace('/common/destiny2_content/screenshots/', '')
        weapon.save()

    damageTypes_objects = DamageTypeDefinition.objects.all()

    for dt in damageTypes_objects:
        dt.iconLink = dt.iconLink.replace('/common/destiny2_content/icons/', '')
        dt.save()


class Migration(migrations.Migration):
    dependencies = [
        ("d2guessrlib", "0002_populate"),
    ]

    operations = [
        UnaccentExtension(),
        migrations.RunPython(correct_tables),
        migrations.RunPython(shorten_links)
    ]
