# Generated by Django 5.0.3 on 2024-05-24 21:39

from django.db import migrations


def trim_img_extensions(apps, schema_editor):
    Weapon = apps.get_model("d2guessrlib", "Weapon")
    DamageTypeDefinition = apps.get_model("d2guessrlib", "DamageTypeDefinition")
    weapon_objects = Weapon.objects.all()
    for weapon in weapon_objects:
        weapon.iconLink = weapon.iconLink.replace('.jpg', '')
        weapon.screenshotLink = weapon.screenshotLink.replace('.jpg', '')
        weapon.save()

    damageTypes_objects = DamageTypeDefinition.objects.all()

    for dt in damageTypes_objects:
        dt.iconLink = dt.iconLink.replace('.png', '')
        dt.save()


class Migration(migrations.Migration):
    dependencies = [
        ("d2guessrlib", "0004_database_corrections_2"),
    ]

    operations = [
        migrations.RunPython(trim_img_extensions)
    ]
